### ISSUE TITLE
touchstart support

### ISSUE THREAD

**Issue by selfagency** [gsantiago/jquery-clickout#1]
please add support for touchstart events, not just click events

thanks!

**Comment by gsantiago** [comment]
I'm gonna work on this.
Thanks!

**Comment by selfagency** [comment]
thank you!

**Comment by selfagency** [comment]
bump

**Comment by gsantiago** [comment]
I have created a new branch called `touchstart`: https://github.com/gsantiago/jquery-clickout/tree/touchstart

@selfagency, could you test it before I merge it into the master?

**Comment by selfagency** [comment]
i am so sorry i never got back to you about this. i just tested it and unfortunately, the touchstart event does not work.

**Comment by seleckis** [comment]
Hello, I used this code insted of yours:
```js
var eventType = 'ontouchend' in document.documentElement
	? 'touchend'
	: 'click';
```
And it works on iOS.
